# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️"

  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "⬆️"

  - package-ecosystem: "npm"
    directory: "/test/type"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/node-extension-cjs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/node-extension-mjs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/node-with-import"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/node-with-require"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/rollup-with-import"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/rollup-with-require"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/webpack-with-import"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/webpack-with-require"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/esbuild-with-import"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/test/esm/esbuild-with-require"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
    ignore:
      # we run this test against a linked version of fast-check
      # by using `yarn link "fast-check"`
      - dependency-name: "fast-check"

  - package-ecosystem: "npm"
    directory: "/.github/actions/deploy-netlify"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "⬆️"
