blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Question / Help
    url: https://github.com/dubzzz/fast-check/discussions/new
    about: Got a question? Head over to Discussions â€” we're happy to help!
